---
kind: pipeline
name: default

steps:
  - name: build
    image: golang
    commands:
      - dep ensure
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o webhook .
   # when:
   #   event:
   #     - push
   #   branch:
   #     - master

  - name: build container
    image: plugins/docker
    settings:
      repo: registry.thobits.lan/drone/admission-webhook
  #  when:
  #    event:
  #      - push
  #    branch:
  #      - master

  #- name: deploy
  #  image: quay.io/ipedrazas/drone-helm
  #  environment:
  #    API_SERVER: https://console.io.thobits.com
  #    KUBERNETES_TOKEN:
  #      from_secret: kubernetes_token
  #  #      DRONE_BUILD_EVENT: push
  #  #      DRONE_COMMIT_SHA: foo123
  #  settings:
  #    chart: ./helm/bb-monitoring
  #    release: bb-monitoring-master
  #    namespace: bb-monitoring
  #    tiller_ns: tiller
  #    wait: true
  #    #dry_run: true
  #    values:
  #      - git.commit_sha=$DRONE_COMMIT_SHA
  #  when:
  #    event:
  #      - push
  #    branch:
  #      - master
